
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor-container"
    ports:
      - "8081:8080"
    volumes:
      - ./shortened_summaries_output_openapi.yaml:/tmp/swagger.yaml
    environment:
      SWAGGER_FILE: /tmp/swagger.yml
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:8082
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=test
      - DB_DATABASE=bookstackapp
    volumes:
      - bookstack_app:/config
    ports:
      - "8082:80"
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=test
    volumes:
      - bookstack_db:/config
    restart: unless-stopped
volumes:
  bookstack_db:
  bookstack_app:

